
source'https://github.com/GoldenChanChan/CCSpecs.git'
source'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'CCSpecialKit_Example' do
  pod 'CCSpecialKit', :path => '../'

  target 'CCSpecialKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
